apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: techdocs
  annotations:
    github.com/project-slug: TerakoyaAcademia/techdocs
    backstage.io/techdocs-ref: url:https://github.com/TerakoyaAcademia/techdocs/mkdocs.yml
spec:
  type: documentation
  lifecycle: experimental
  owner: terakoya_academia
